server:
  env: "local"
  host: "localhost"
  port: "8082"
  timeout: 4
  idle_timeout: 60

database:
  host: "localhost"
  port:  "5433"
  user: "postgres"
  password: "postgres"
  name: "subscriptions"
  sslmode: "disable"