server:
  env: "local"
  host: "localhost"
  port: "8080"
  timeout: 4
  idle_timeout: 60

database:
  host: "localhost"
  port:  "5430"
  user: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"
  maxconns: 20
  minconns: 5
  maxconnlifetime: 30
  maxconnidletime: 5
  healthcheckperiod: 1